/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BreederService } from "../breeder.service";
import { BreederCreateInput } from "./BreederCreateInput";
import { Breeder } from "./Breeder";
import { BreederFindManyArgs } from "./BreederFindManyArgs";
import { BreederWhereUniqueInput } from "./BreederWhereUniqueInput";
import { BreederUpdateInput } from "./BreederUpdateInput";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { MessageWhereUniqueInput } from "../../message/base/MessageWhereUniqueInput";

export class BreederControllerBase {
  constructor(protected readonly service: BreederService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Breeder })
  async createBreeder(
    @common.Body() data: BreederCreateInput
  ): Promise<Breeder> {
    return await this.service.createBreeder({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        profilePhoto: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Breeder] })
  @ApiNestedQuery(BreederFindManyArgs)
  async breeders(@common.Req() request: Request): Promise<Breeder[]> {
    const args = plainToClass(BreederFindManyArgs, request.query);
    return this.service.breeders({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        profilePhoto: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Breeder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async breeder(
    @common.Param() params: BreederWhereUniqueInput
  ): Promise<Breeder | null> {
    const result = await this.service.breeder({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        profilePhoto: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Breeder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBreeder(
    @common.Param() params: BreederWhereUniqueInput,
    @common.Body() data: BreederUpdateInput
  ): Promise<Breeder | null> {
    try {
      return await this.service.updateBreeder({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          profilePhoto: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Breeder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBreeder(
    @common.Param() params: BreederWhereUniqueInput
  ): Promise<Breeder | null> {
    try {
      return await this.service.deleteBreeder({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          profilePhoto: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/messages")
  @ApiNestedQuery(MessageFindManyArgs)
  async findMessages(
    @common.Req() request: Request,
    @common.Param() params: BreederWhereUniqueInput
  ): Promise<Message[]> {
    const query = plainToClass(MessageFindManyArgs, request.query);
    const results = await this.service.findMessages(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        content: true,
        sentAt: true,

        ad: {
          select: {
            id: true,
          },
        },

        breeder: {
          select: {
            id: true,
          },
        },

        buyer: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/messages")
  async connectMessages(
    @common.Param() params: BreederWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        connect: body,
      },
    };
    await this.service.updateBreeder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/messages")
  async updateMessages(
    @common.Param() params: BreederWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        set: body,
      },
    };
    await this.service.updateBreeder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/messages")
  async disconnectMessages(
    @common.Param() params: BreederWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        disconnect: body,
      },
    };
    await this.service.updateBreeder({
      where: params,
      data,
      select: { id: true },
    });
  }
}
