/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BuyerService } from "../buyer.service";
import { BuyerCreateInput } from "./BuyerCreateInput";
import { Buyer } from "./Buyer";
import { BuyerFindManyArgs } from "./BuyerFindManyArgs";
import { BuyerWhereUniqueInput } from "./BuyerWhereUniqueInput";
import { BuyerUpdateInput } from "./BuyerUpdateInput";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { MessageWhereUniqueInput } from "../../message/base/MessageWhereUniqueInput";

export class BuyerControllerBase {
  constructor(protected readonly service: BuyerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Buyer })
  async createBuyer(@common.Body() data: BuyerCreateInput): Promise<Buyer> {
    return await this.service.createBuyer({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        profilePhoto: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Buyer] })
  @ApiNestedQuery(BuyerFindManyArgs)
  async buyers(@common.Req() request: Request): Promise<Buyer[]> {
    const args = plainToClass(BuyerFindManyArgs, request.query);
    return this.service.buyers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        profilePhoto: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Buyer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async buyer(
    @common.Param() params: BuyerWhereUniqueInput
  ): Promise<Buyer | null> {
    const result = await this.service.buyer({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        profilePhoto: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Buyer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBuyer(
    @common.Param() params: BuyerWhereUniqueInput,
    @common.Body() data: BuyerUpdateInput
  ): Promise<Buyer | null> {
    try {
      return await this.service.updateBuyer({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          profilePhoto: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Buyer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBuyer(
    @common.Param() params: BuyerWhereUniqueInput
  ): Promise<Buyer | null> {
    try {
      return await this.service.deleteBuyer({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          profilePhoto: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/messages")
  @ApiNestedQuery(MessageFindManyArgs)
  async findMessages(
    @common.Req() request: Request,
    @common.Param() params: BuyerWhereUniqueInput
  ): Promise<Message[]> {
    const query = plainToClass(MessageFindManyArgs, request.query);
    const results = await this.service.findMessages(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        content: true,
        sentAt: true,

        ad: {
          select: {
            id: true,
          },
        },

        breeder: {
          select: {
            id: true,
          },
        },

        buyer: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/messages")
  async connectMessages(
    @common.Param() params: BuyerWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        connect: body,
      },
    };
    await this.service.updateBuyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/messages")
  async updateMessages(
    @common.Param() params: BuyerWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        set: body,
      },
    };
    await this.service.updateBuyer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/messages")
  async disconnectMessages(
    @common.Param() params: BuyerWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        disconnect: body,
      },
    };
    await this.service.updateBuyer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
